# Generated by Django 6.0 on 2026-01-05 19:49

import datetime
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US')),
                ('email', models.EmailField(max_length=254)),
                ('heard_from', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(default=datetime.time(10, 0))),
                ('location', models.CharField(choices=[('north', 'North Campus (Francis Tuttle)'), ('south', 'South Campus (MNTC, S. Penn)')], max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], max_length=9)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='registered', max_length=10)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slts.attendee')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slts.seminar')),
            ],
        ),
    ]
