# Generated by Django 6.0 on 2026-01-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='heard_from',
            field=models.CharField(choices=[('friend', 'Friend'), ('edmond l and l', 'Edmond L&L'), ('bethany tribune', 'Bethany Tribune'), ('other newspaper', 'Other Newspaper'), ('flyer', 'Flyer'), ('facebook', 'Facebook'), ('website', 'Website'), ('youtube', 'YouTube'), ('mailout', 'Mailout'), ('seminar feedback', 'Feedback Form / Seminar')], max_length=16),
        ),
    ]
