# Generated by Django 6.0 on 2026-01-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0002_alter_attendee_heard_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='heard_from',
            field=models.CharField(choices=[('friend', 'Friend'), ('edmond l and l', 'Edmond L&L'), ('bethany tribune', 'Bethany Tribune'), ('other newspaper', 'Other Newspaper'), ('flyer', 'Flyer'), ('facebook', 'Facebook'), ('website', 'Website'), ('youtube', 'YouTube'), ('mailout', 'Mailout'), ('seminar feedback', 'Feedback Form / Seminar')], max_length=16, verbose_name='Heard About Us From'),
        ),
    ]
