# Generated by Django 6.0 on 2026-01-05 19:57

import localflavor.us.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0003_rename_fname_attendee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='state',
            field=localflavor.us.models.USStateField(default='OK', max_length=2),
        ),
    ]
