# Generated by Django 6.0 on 2026-01-06 01:06

import localflavor.us.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0004_alter_attendee_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='heard_from',
            field=models.CharField(blank=True, choices=[('friend', 'Friend'), ('edmond l and l', 'Edmond L&L'), ('bethany tribune', 'Bethany Tribune'), ('other newspaper', 'Other Newspaper'), ('flyer', 'Flyer'), ('facebook', 'Facebook'), ('website', 'Website'), ('youtube', 'YouTube'), ('mailout', 'Mailout'), ('seminar feedback', 'Feedback Form / Seminar')], max_length=16, verbose_name='Heard About Us From'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
