# Generated by Django 6.0 on 2026-01-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0005_alter_attendee_address_alter_attendee_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
    ]
