# Generated by Django 6.0 on 2026-01-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0006_alter_seminar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
