# Generated by Django 6.0.1 on 2026-01-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0008_registrationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, upload_to='seminars/'),
        ),
    ]
