# Generated by Django 6.0.1 on 2026-01-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0009_seminar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
