# Generated by Django 6.0.1 on 2026-01-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0010_alter_attendee_address_alter_attendee_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
