# Generated by Django 6.0.1 on 2026-01-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0011_alter_attendee_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationToken',
        ),
    ]
