# Generated by Django 6.0.1 on 2026-01-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0013_educationpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
    ]
