# Generated by Django 6.0.1 on 2026-01-19 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0014_registration_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationpartner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='slts.attendee'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='seminar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='slts.seminar'),
        ),
    ]
