# Generated by Django 6.0.1 on 2026-01-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0015_educationpartner_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='handout',
            field=models.FileField(blank=True, upload_to='seminar-handouts/'),
        ),
    ]
