# Generated by Django 6.0.1 on 2026-01-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0016_seminar_handout'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationpartner',
            name='partner_location',
            field=models.CharField(blank=True, choices=[('north', 'Education Partner for North Campus ONLY'), ('south', 'Education Partner for South Campus ONLY'), ('both', 'Education Partner for BOTH Campuses')], max_length=5),
        ),
    ]
