# Generated by Django 6.0.1 on 2026-01-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0017_educationpartner_partner_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationpartner',
            name='partner_location',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('both', 'Both')], max_length=5),
        ),
    ]
