# Generated by Django 6.0.1 on 2026-01-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0019_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('review', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='FAQs',
            new_name='FAQ',
        ),
    ]
