# Generated by Django 6.0.1 on 2026-02-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0021_attendee_married_to_attendee_notes_attendee_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationpartner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='heard_from',
            field=models.CharField(blank=True, choices=[('friend', 'Friend'), ('edmond l and l', 'Edmond L&L'), ('bethany tribune', 'Bethany Tribune'), ('other newspaper', 'Other Newspaper'), ('news station', 'News Station'), ('flyer', 'Flyer'), ('facebook', 'Facebook'), ('website', 'Website'), ('youtube', 'YouTube'), ('internet', 'Internet'), ('mailout', 'Mailout'), ('seminar feedback', 'Feedback Form / Seminar'), ('education partner', 'Education Partner')], max_length=17, verbose_name='Heard About Us From'),
        ),
    ]
