# Generated by Django 6.0.1 on 2026-02-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0022_educationpartner_active_alter_attendee_heard_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationpartner',
            old_name='description',
            new_name='notes',
        ),
    ]
