# Generated by Django 6.0.1 on 2026-02-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0023_rename_description_educationpartner_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='local',
            field=models.BooleanField(default=True),
        ),
    ]
