# Generated by Django 6.0.1 on 2026-02-05 03:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0024_attendee_deceased_attendee_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('tour', 'Tour'), ('exin', 'Expert Insights')], max_length=4)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=datetime.time(10, 0))),
                ('location', models.CharField(choices=[('north', 'North Campus (Francis Tuttle)'), ('south', 'South Campus (MNTC, S. Penn)')], max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], max_length=9)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='registered', max_length=10)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventRegistrations', to='slts.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventRegistrations', to='slts.otherevent')),
            ],
        ),
    ]
