# Generated by Django 6.0.1 on 2026-02-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0025_otherevent_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
