# Generated by Django 6.0.1 on 2026-05-13 15:04

import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0026_attendee_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='otherevent',
            name='location',
        ),
        migrations.AddField(
            model_name='otherevent',
            name='address',
            field=models.CharField(default='123 N Avenue', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherevent',
            name='city',
            field=models.CharField(default='OKC', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherevent',
            name='state',
            field=localflavor.us.models.USStateField(default='OK', max_length=2),
        ),
        migrations.AddField(
            model_name='otherevent',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
