# Generated by Django 6.0.1 on 2026-05-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0027_alter_attendee_options_remove_otherevent_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='rating',
        ),
    ]
