# Generated by Django 6.0.1 on 2026-05-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0028_remove_registration_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.CharField(choices=[('north', 'North Campus (Francis Tuttle)'), ('south', 'South Campus (MNTC, S. Penn)'), ('new_north', 'North Campus (Portland)')], max_length=9),
        ),
    ]
