# Generated by Django 6.0.1 on 2026-09-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0029_alter_seminar_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=60)),
                ('series', models.CharField(choices=[('north', 'North'), ('south', 'South')], max_length=5)),
                ('email_signature', models.TextField()),
                ('color', models.CharField(choices=[('purple', 'Purple (Primary)'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('blue', 'Blue'), ('green', 'Green'), ('lime', 'Lime')], max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='seminar',
            name='location_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='slts.location'),
        ),
    ]
