# Generated by Django 6.0.1 on 2026-09-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0030_location_seminar_location_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='location_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='slts.location', verbose_name='Location'),
            preserve_default=False,
        ),
    ]
