# Generated by Django 6.0.1 on 2026-09-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0031_alter_seminar_location_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='short_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='email_signature',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='111 North Street', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='Oklahoma City', max_length=20),
            preserve_default=False,
        ),
    ]
