# Generated by Django 6.0.1 on 2026-09-05 17:16

import localflavor.us.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0032_rename_short_name_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=localflavor.us.models.USStateField(default='OK', max_length=2),
        ),
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(default=73170, max_length=10),
            preserve_default=False,
        ),
    ]
