# Generated by Django 6.0.1 on 2026-09-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0033_location_state_location_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='full_name',
            field=models.CharField(default='Full name', max_length=100),
            preserve_default=False,
        ),
    ]
