# Generated by Django 6.0.1 on 2026-09-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0034_location_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='location',
        ),
    ]
