# Generated by Django 6.0.1 on 2026-09-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0035_remove_seminar_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'verbose_name': 'Other Event Registration', 'verbose_name_plural': 'Other Event Registrations'},
        ),
    ]
