# Generated by Django 6.0.1 on 2026-09-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slts', '0036_alter_eventregistration_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_name', models.CharField(max_length=200)),
                ('article_title', models.CharField(max_length=300)),
                ('article_url', models.URLField(max_length=500)),
                ('published_date', models.DateField()),
                ('excerpt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=9)),
            ],
        ),
    ]
