"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ as django_environ
import os


djenv = django_environ.Env(
    DEBUG=(bool, False)
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


djenv.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = djenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = djenv('DEBUG')
ALLOWED_HOSTS = djenv.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'slts.apps.SltsConfig', # SLTS custom app
    'localflavor',          # for US state codes and zip codes
    'phonenumber_field',    # for phone numbers for attendees
    'taggit',               # for tag fields for attendees
    'widget_tweaks',        # for auto gen form customization (complete_registration.html)
    'django_daisy',         # for nice looking admin UI
    'django_summernote',    # for rich text editing (seminar descriptions)
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': djenv("DB_ENGINE"),
        'NAME': djenv("DB_NAME"),
        'USER': djenv("DB_USER"),
        'PASSWORD': djenv("DB_PASSWORD"),
        'HOST': djenv("DB_HOST"),
        'PORT': djenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static",]
STATIC_ROOT = djenv("STATIC_ROOT")


# Media files (User uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = djenv("MEDIA_ROOT")


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# Email Settings
EMAIL_HOST = djenv("EMAIL_HOST")
EMAIL_HOST_USER = djenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = djenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = djenv("EMAIL_PORT")
EMAIL_USE_TLS = djenv("EMAIL_USE_TLS")
EMAIL_BACKEND = djenv("EMAIL_BACKEND")
DEFAULT_FROM_EMAIL = djenv("DEFAULT_FROM_EMAIL")


# URL Settings
SITE_URL = djenv('SITE_URL')



# django-richtextfield settings
DJRICHTEXTFIELD_CONFIG = {
    'js': ['//cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js'],
    'init_template': 'djrichtextfield/init/tinymce.js',
    'settings': {
        'menubar': False,
        'plugins': 'link image',
        'toolbar': 'bold italic | link image | removeformat',
        'width': 700
    }
}


# admin ui package settings
JAZZMIN_SETTINGS = {
    "site_brand": "SLTS Admin",
    "site_title": "SLTS Admin",
    "site_header": "SLTS Dashboard",
    "welcome_sign": "Welcome to SLTS Administration",
    "copyright": "Senior Living Truth Series",
    "search_model": "auth.User",
    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
    ],
}
